[build]
  command = "npm ci --only=production"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 3

[environments.production.variables]
  NODE_ENV = "production"
