[build]
  command = "npm install"

[deploy]
  startCommand = "npm start"
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10

[environments.production.variables]
  NODE_ENV = "production"